server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    prefer-ip-address: true